use_frameworks!

target 'SevenPictureBrowsing_Example' do
  pod 'SevenPictureBrowsing', :path => '../'

  target 'SevenPictureBrowsing_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
